#!/bin/bash

for var in "$@"; do echo "$var"; done | sort -r  | while read -r f; do
    test ! -f "$f" && echo "File '$f' doesn't exist" > /dev/stderr && continue

    logfile=${f%.*}

    date=''
    while read l; do
        l_date=$(echo $l | awk '{print $1 " " $2}')
        if [ "$l_date" != "$date" ]; then
            #echo $l_date
            logfile_date=$(date -d "$l_date" "+%y%m%d")
            date=$l_date
        fi
        echo "$l" >> $logfile.$logfile_date
    done < $f

    rm $f
done